### ISSUE TITLE
Support Python 3.14 problem

### ISSUE THREAD

**Issue by eiffelcn** [Textualize/textual-serve#36]
On a brand new project created by uv, that only include Python 3.14, textual, textual-serve, textual-dev. The example command 'uv run textual serve "python -m textual"' will reply "RuntimeError: There is no current event loop in thread 'MainThread'." But everything works fine when switching to Python 3.13.

`uv init testproject -p 3.14               # switch to 3.13, everything works fine`
`cd testproject`
`uv add textual textual-dev textual-serve`
`uv run textual serve "python -m textual"   # Fail for "RuntimeError: There is no current event loop in thread 'MainThread'."`

**Comment by AbstractUmbra** [comment]
Seconded on this one:
<details>
<summary>Code</summary>

```py
import os

try:
    from textual_serve.server import Server
except ModuleNotFoundError:
    raise RuntimeError("The `web` extra is required to use the web extension.") from None

PORT = int(os.getenv("YUREI_PORT", "8000"))
HOST = os.getenv("YUREI_BIND_ADDRESS", "localhost")

__all__ = ("run_server",)


def run_server() -> None:
    server = Server("yurei", host=HOST, port=PORT)
    server.serve()
```
</details>

<details>
<summary>Exception</summary>

```py
❯ yurei-web
Traceback (most recent call last):
  File "/home/penumbra/projects/phas/.venv/bin/yurei-web", line 10, in <module>
    sys.exit(web_entry())
             ~~~~~~~~~^^
  File "/home/penumbra/projects/phas/yurei/tui/__init__.py", line 14, in web_entry
    run_server()
    ~~~~~~~~~~^^
  File "/home/penumbra/projects/phas/yurei/tui/web.py", line 16, in run_server
    server.serve()
    ~~~~~~~~~~~~^^
  File "/home/penumbra/projects/phas/.venv/lib/python3.14/site-packages/textual_serve/server.py", line 216, in serve
    loop = asyncio.get_event_loop()
  File "/home/penumbra/.local/share/uv/python/cpython-3.14.0b3-linux-x86_64-gnu/lib/python3.14/asyncio/events.py", line 718, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.
```
</details>

I have this built as a script/"binary" with uv, hence the shortcut names etc.

**Comment by sreyemnayr** [comment]
Suspect it is essentially the same issue that was sorted here? https://github.com/Textualize/textual/pull/5799

**Comment by TomJGooding** [comment]
Try updating all textual packages to the latest versions. For textual-serve it looks like this was fixed in fa5cf5f.

**Comment by sreyemnayr** [comment]
That didn't fully fix it for 3.14, but I submitted PR #37 that does. I just didn't have time to fully discover everything that needs testing, so it needs review for sure.

**Comment by TomJGooding** [comment]
I was reminded of this issue when my system Python upgraded to 3.14. From a quick test I can't reproduce this with textual-serve 1.1.3?

```bash
$ python --version
Python 3.14.2
$ mkdir test-serve && cd "$_"
$ python -m venv .venv
$ source .venv/bin/activate
(.venv) $ python -m pip install textual textual-dev textual-serve
(.venv) $ pip freeze | grep "textual"
textual==8.0.0
textual-dev==1.8.0
textual-serve==1.1.3
(.venv) $ textual serve "python -m textual"
```
